/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckboxGroup: typeof import('@arco-design/web-vue')['CheckboxGroup']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    APagination: typeof import('@arco-design/web-vue')['Pagination']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ASkeleton: typeof import('@arco-design/web-vue')['Skeleton']
    ASkeletonLine: typeof import('@arco-design/web-vue')['SkeletonLine']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    AUpload: typeof import('@arco-design/web-vue')['Upload']
    CreateTopic: typeof import('./src/components/CreateTopic/CreateTopic.vue')['default']
    Debate: typeof import('./src/components/Debate/Debate.vue')['default']
    DebateItem: typeof import('./src/components/Debate/DebateItem.vue')['default']
    DebateTextArea: typeof import('./src/components/Debate/DebateTextArea.vue')['default']
    DebateTopBar: typeof import('./src/components/Debate/DebateTopBar.vue')['default']
    Empty: typeof import('./src/components/Empty/Empty.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    LoadMore: typeof import('./src/components/LoadMore/LoadMore.vue')['default']
    Mask: typeof import('./src/components/Mask/Mask.vue')['default']
    MdEditor: typeof import('./src/components/MdEditor/MdEditor.vue')['default']
    MdViewer: typeof import('./src/components/MdViewer/MdViewer.vue')['default']
    RankingItem: typeof import('./src/components/Ranking/RankingItem.vue')['default']
    RankingList: typeof import('./src/components/Ranking/RankingList.vue')['default']
    RecordItem: typeof import('./src/components/Record/RecordItem.vue')['default']
    RecordList: typeof import('./src/components/Record/RecordList.vue')['default']
    ReturnHome: typeof import('./src/components/ReturnHome/ReturnHome.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('./src/components/ScrollTop/ScrollTop.vue')['default']
    Skeleton: typeof import('./src/components/Skeleton/Skeleton.vue')['default']
    StartDebate: typeof import('./src/components/StartDebate/StartDebate.vue')['default']
    Switch: typeof import('./src/components/Switch/Switch.vue')['default']
    Switch2: typeof import('./src/components/Switch/Switch2.vue')['default']
    SwitchOld: typeof import('./src/components/Switch/Switch-old.vue')['default']
    TagItem: typeof import('./src/components/Tag/TagItem.vue')['default']
    TagList: typeof import('./src/components/Tag/TagList.vue')['default']
    ToggleDark: typeof import('./src/components/ToggleDark/ToggleDark.vue')['default']
    TopBarPC: typeof import('./src/components/Debate/TopBar/TopBarPC.vue')['default']
    TopBarPhone: typeof import('./src/components/Debate/TopBar/TopBarPhone.vue')['default']
    TopicItem: typeof import('./src/components/Topic/TopicItem.vue')['default']
    TopicList: typeof import('./src/components/Topic/TopicList.vue')['default']
  }
}
