/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ASkeleton: typeof import('@arco-design/web-vue')['Skeleton']
    ASkeletonLine: typeof import('@arco-design/web-vue')['SkeletonLine']
    ASkeletonShape: typeof import('@arco-design/web-vue')['SkeletonShape']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    AUpload: typeof import('@arco-design/web-vue')['Upload']
    Loading: typeof import('./src/components/loading/index.vue')['default']
    LoadMore: typeof import('./src/components/load-more/index.vue')['default']
    MdEditor: typeof import('./src/components/MdEditor/index.vue')['default']
    MdViewer: typeof import('./src/components/MdViewer/index.vue')['default']
    Ranking: typeof import('./src/components/Ranking/index.vue')['default']
    RankingItem: typeof import('./src/components/Ranking/RankingItem.vue')['default']
    RankingList: typeof import('./src/components/Ranking/RankingList.vue')['default']
    ReturnHome: typeof import('./src/components/return-home/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartDebate: typeof import('./src/components/start-debate/index.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TChat: typeof import('tdesign-vue-next')['Chat']
    TChatContent: typeof import('tdesign-vue-next')['ChatContent']
    TChatLoading: typeof import('tdesign-vue-next')['ChatLoading']
    TChatReasoning: typeof import('tdesign-vue-next')['ChatReasoning']
    TChatSender: typeof import('tdesign-vue-next')['ChatSender']
    ToggleDark: typeof import('./src/components/toggle-dark/index.vue')['default']
    Topic: typeof import('./src/components/Topic/index.vue')['default']
    TopicItem: typeof import('./src/components/Topic/TopicItem.vue')['default']
    TopicList: typeof import('./src/components/Topic/TopicList.vue')['default']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  }
}
